import { seedCollection } from '../seedUtils.js';

const races = [
  {
    id: 'human',
    label: 'Humain',
    hpBonus: 0,
    dodgeBonus: 0,
    armorBonus: 0,
    perceptionBonus: 0,
    defaultLuck: 1,
    ignoreWeightDodgeMalus: false,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: false,
    notes: 'Esprit d’aventure',
  },
  {
    id: 'queldorei',
    label: 'Quel’dorei',
    hpBonus: 0,
    dodgeBonus: 0,
    armorBonus: 0,
    perceptionBonus: 10,
    ressourceBonus: 10,
    defaultLuck: 0,
    ignoreWeightDodgeMalus: false,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: false,
  },
  {
    id: 'rendorei',
    label: 'Ren’dorei',
    hpBonus: 0,
    dodgeBonus: 0,
    armorBonus: 0,
    perceptionBonus: 10,
    defaultLuck: 0,
    ignoreWeightDodgeMalus: false,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: false,
  },
  {
    id: 'kaldorei',
    label: 'Kaldorei',
    hpBonus: 0,
    dodgeBonus: 0,
    armorBonus: 0,
    perceptionBonus: 20,
    defaultLuck: 0,
    ignoreWeightDodgeMalus: true,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: false,
  },
  {
    id: 'dwarf-bronzebeard',
    label: 'Nain - Barbe-de-Bronze',
    hpBonus: 10,
    dodgeBonus: 0,
    armorBonus: 2,
    perceptionBonus: 0,
    defaultLuck: 0,
    ignoreWeightDodgeMalus: false,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: true,
  },
  {
    id: 'dwarf-darkiron',
    label: 'Nain - Sombrefer',
    hpBonus: 10,
    dodgeBonus: 0,
    armorBonus: 0,
    perceptionBonus: 0,
    defaultLuck: 0,
    ignoreWeightDodgeMalus: false,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: true,
  },
  {
    id: 'dwarf-wildhammer',
    label: 'Nain - Marteau-Hardi',
    hpBonus: 10,
    dodgeBonus: 0,
    armorBonus: 0,
    perceptionBonus: 0,
    defaultLuck: 0,
    ignoreWeightDodgeMalus: false,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: true,
  },
  {
    id: 'earthen',
    label: 'Terrestre',
    hpBonus: 0,
    dodgeBonus: 0,
    armorBonus: 2,
    perceptionBonus: 0,
    defaultLuck: 0,
    ignoreWeightDodgeMalus: false,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: true,
    requiredWeightIds: ['very-heavy', 'anvil'],
    requiredMusculatureIds: ['solide', 'imposante', 'colossale'],
  },
  {
    id: 'gnome',
    label: 'Gnome',
    hpBonus: 0,
    dodgeBonus: 5,
    armorBonus: 0,
    perceptionBonus: 0,
    defaultLuck: 0,
    dodgeCapBonus: 15,
    ignoreWeightDodgeMalus: false,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: false,
  },
  {
    id: 'mechagnome',
    label: 'Mécagnome',
    hpBonus: 0,
    dodgeBonus: 5,
    armorBonus: 0,
    perceptionBonus: 0,
    defaultLuck: 0,
    dodgeCapBonus: 15,
    ignoreWeightDodgeMalus: false,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: false,
    requiredMusculatureIds: ['rachitique'],
  },
  {
    id: 'worgen',
    label: 'Worgen',
    hpBonus: 0,
    dodgeBonus: 0,
    armorBonus: 0,
    perceptionBonus: 0,
    defaultLuck: 0,
    ignoreWeightDodgeMalus: true,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: false,
  },
  {
    id: 'pandaren',
    label: 'Pandaren',
    hpBonus: 0,
    dodgeBonus: 0,
    armorBonus: 0,
    perceptionBonus: 0,
    defaultLuck: 0,
    ignoreWeightDodgeMalus: true,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: false,
  },
  {
    id: 'draenei',
    label: 'Draeneï',
    hpBonus: 0,
    dodgeBonus: 0,
    armorBonus: 0,
    perceptionBonus: 0,
    defaultLuck: 0,
    ignoreWeightDodgeMalus: false,
    ignoreWeightDodgeBonus: false,
    ignoreSizeDodgeBonus: false,
  },
];

await seedCollection('races', races);
